# Generated by Django 2.1.3 on 2019-02-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('label_id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('label_name', models.CharField(max_length=10, verbose_name='分类标签')),
            ],
            options={
                'verbose_name': '歌曲分类',
                'verbose_name_plural': '歌曲分类',
            },
        ),
    ]
